## Configuración general

Esto es configuración general de IPython

In [2]:
%config InlineBackend.close_figures=False
%matplotlib inline
from matplotlib import interactive
interactive(False)

Reloading matplotlib.backends.__future__
Reloading __future__
Reloading matplotlib.backends.matplotlib
Reloading matplotlib
Reloading matplotlib.__future__
Reloading matplotlib.sys
Reloading matplotlib.dateutil
Reloading dateutil
Reloading matplotlib.pyparsing
Reloading pyparsing
Reloading string
Reloading re
Reloading sre_compile
Reloading _sre
Reloading sre_parse
Reloading sre_constants
Reloading _locale
Reloading copy_reg
Reloading types
Reloading strop
Reloading weakref
Reloading UserDict
Reloading _abcoll
Reloading abc
Reloading _weakrefset
Reloading _weakref
Reloading exceptions
Reloading copy
Reloading org
Reloading warnings
Reloading linecache
Reloading os
Reloading errno
Reloading posix
Reloading posixpath
Reloading stat
Reloading genericpath
Reloading _warnings
Reloading collections
Reloading _collections
Reloading operator
Reloading keyword
Reloading heapq
Reloading itertools
Reloading _heapq
Reloading thread
Reloading pprint
Reloading cStringIO
Reloading functools
Reloading

Luego importamos todo las "clases" que provee la librería `sur`

In [1]:
from sur import *

setup_database()

/home/tin/.virtualenvs/sur/local/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


## Definición de la mezcla

In [5]:
mi_mezcla = Mixture(name="tal cosa")
mi_mezcla.add('methane', .4) 
mi_mezcla['ethane'] = .3
mi_mezcla['co2'] = .2002
mi_mezcla.add('water')
mi_mezcla.compounds


[<Compound: METHANE>, <Compound: ETHANE>, <Compound: CARBON DIOXIDE>, <Compound: WATER>]

In [6]:
mi_mezcla.sort(True)   # ordena por peso

In [7]:
mi_mezcla.compounds

[<Compound: METHANE>, <Compound: WATER>, <Compound: ETHANE>, <Compound: CARBON DIOXIDE>]

## Definición de la configuración (RKPR)

In [8]:
EosSetup??

In [10]:
setup = EosSetup.objects.create(eos='PR', kij_mode=EosSetup.CONSTANTS,  lij_mode=EosSetup.ZERO)
setup.set_interaction('kij', 'methane', 'co2', .1)
setup.set_interaction('kij', 'co2', 'n-decane',  0.091)
setup.set_interaction('lij', 'co2', 'n-decane',  -0.90)

<LijInteractionParameter: PR [<Compound: n-DECANE>, <Compound: CARBON DIOXIDE>, <Compound: CARBON DIOXIDE>, <Compound: CARBON DIOXIDE>]: -0.9>

In [14]:
setup.kij(mi_mezcla)

array([[ 0.    ,  0.    ,  0.0114,  0.1   ],
       [ 0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.0114,  0.    ,  0.    ,  0.1184],
       [ 0.1   ,  0.    ,  0.1184,  0.    ]])

In [16]:
matriz = """0. .2 .3 .4
0 0 -.1 .2
0 0 -.3 .12
0 0 -.12 .21"""


In [17]:
setup.set_interaction_matrix('kij', mi_mezcla, matriz)

Podemos ver como van quedando nuestras matrices de interacción para la mezcla `m`

In [18]:
setup.kij(mi_mezcla)

array([[ 0.  ,  0.2 ,  0.3 ,  0.4 ],
       [ 0.2 ,  0.  , -0.1 ,  0.2 ],
       [ 0.3 , -0.1 ,  0.  ,  0.12],
       [ 0.4 ,  0.2 ,  0.12,  0.  ]])

## Simulación de la envolvente para la mezcla con la configuración dada

Para simular una envolvente se llama al método `get_envelope` de la mezcla con una configuración

In [2]:
%matplotlib inline

Reloading __future__
Reloading matplotlib
Reloading matplotlib.externals
Reloading distutils
Reloading distutils.os
Reloading os
Reloading errno
Reloading posix
Reloading posixpath
Reloading stat
Reloading genericpath
Reloading warnings
Reloading linecache
Reloading types
Reloading _warnings
Reloading UserDict
Reloading _abcoll
Reloading abc
Reloading _weakrefset
Reloading _weakref
Reloading copy_reg
Reloading distutils.sys
Reloading distutils.warnings
Reloading distutils.imp
Reloading imp
Reloading distutils.opcode
Reloading opcode
Reloading distutils.distutils
Reloading distutils.version
Reloading distutils.string
Reloading string
Reloading re
Reloading sre_compile
Reloading _sre
Reloading sre_parse
Reloading sre_constants
Reloading _locale
Reloading strop
Reloading distutils.re
Reloading distutils.types
Reloading itertools
Reloading io
Reloading _io
Reloading inspect
Reloading dis
Reloading tokenize
Reloading token
Reloading operator
Reloading collections
Reloading _collections
Relo

ImportError: No module named moves

In [3]:
m = Mixture()
m.add_many("methane co2 n-decane", "0.25 0.50 0.25")
s = EosSetup.objects.create(eos='RKPR', kij_mode='constants',
                            lij_mode='constants')
s.set_interaction('kij', 'methane', 'co2', .1)
s.set_interaction('kij', 'co2', 'n-decane',  0.091)
env = m.get_envelope(s)

In [9]:
%matplotlib notebook

Reloading __future__
Reloading matplotlib
Reloading matplotlib.externals
Reloading distutils
Reloading distutils.os
Reloading os
Reloading errno
Reloading posix
Reloading posixpath
Reloading stat
Reloading genericpath
Reloading warnings
Reloading linecache
Reloading types
Reloading _warnings
Reloading UserDict
Reloading _abcoll
Reloading abc
Reloading _weakrefset
Reloading _weakref
Reloading copy_reg
Reloading distutils.sys
Reloading distutils.warnings
Reloading distutils.imp
Reloading imp
Reloading distutils.opcode
Reloading opcode
Reloading distutils.distutils
Reloading distutils.version
Reloading distutils.string
Reloading string
Reloading re
Reloading sre_compile
Reloading _sre
Reloading sre_parse
Reloading sre_constants
Reloading _locale
Reloading strop
Reloading distutils.re
Reloading distutils.types
Reloading itertools
Reloading io
Reloading _io
Reloading inspect
Reloading dis
Reloading tokenize
Reloading token
Reloading operator
Reloading collections
Reloading _collections
Relo

ImportError: No module named moves

In [11]:
import matplotlib

In [12]:
matplotlib.__version__

'1.5.1'

In [4]:
env.plot()

TypeError: unbound method __init__() must be called with UserDict instance as first argument (got WeakValueDictionary instance instead)

In [6]:
env.plot()

TypeError: unbound method __init__() must be called with UserDict instance as first argument (got WeakValueDictionary instance instead)

In [19]:
env = mi_mezcla.get_envelope(setup)

/home/tin/.virtualenvs/sur/local/lib/python2.7/site-packages/numpy/lib/npyio.py:809: UserWarning: loadtxt: Empty input file: "<cStringIO.StringI object at 0x7efdc6cdf030>"
  warnings.warn('loadtxt: Empty input file: "%s"' % fname)


en `env` (variable) tenemos la envolvente. Podemos consultar, por ejemplo, sus atributos temperatura, presión, etc.





In [22]:
env.p

array([  1.44200000e-02,   1.64600000e-02,   2.01600000e-02,
         2.45700000e-02,   2.97800000e-02,   3.59200000e-02,
         4.31100000e-02,   5.14700000e-02,   6.11500000e-02,
         7.22700000e-02,   8.49900000e-02,   9.94400000e-02,
         1.15800000e-01,   1.34100000e-01,   1.54500000e-01,
         1.77100000e-01,   2.02000000e-01,   2.29200000e-01,
         2.58800000e-01,   2.90700000e-01,   3.24900000e-01,
         4.05600000e-01,   5.23400000e-01,   6.71100000e-01,
         8.54900000e-01,   1.08200000e+00,   1.36100000e+00,
         1.70100000e+00,   2.11100000e+00,   2.60400000e+00,
         3.19200000e+00,   3.88700000e+00,   4.70400000e+00,
         5.65700000e+00,   6.75900000e+00,   8.02800000e+00,
         9.47500000e+00,   1.11200000e+01,   1.29700000e+01,
         1.50400000e+01,   1.73400000e+01,   1.98900000e+01,
         2.26900000e+01,   2.57500000e+01,   2.90700000e+01,
         3.26600000e+01,   3.65200000e+01,   4.06600000e+01,
         4.50600000e+01,

In [25]:
print(env.input_txt)

3		NC
0.25  0.5  0.25  		z1,z2...zNC
3				NMODEL (1:SRK / 2:PR / 3:RKPR)
0  0			ncomb, nTdep
METHANE(1)
190.564  45.99 0.0115478  0.116530154855 1.16          tc, pc, ohm, vc, zrat
2.30376807604   0.0304337956072   0.5   1.54083758839		ac, b, delta1, k
CARBON DIOXIDE(2)
304.21  73.83 0.223621  0.109039999995 1.16          tc, pc, ohm, vc, zrat
3.85211219359   0.027914651867   1.85325193495   2.20290185161		ac, b, delta1, k
0.1 		kij
0.0 		lij
n-DECANE(3)
617.7  21.1 0.492328  0.756468369911 1.16          tc, pc, ohm, vc, zrat
56.6610724692   0.192140038284   2.239538   3.11337933794		ac, b, delta1, k
0.0   0.091 		kij
-0.145519   0.0 		lij




In [27]:
print(env.output_txt)

METHANE(1)        
Tc= 190.5640   Pc =  45.9900   Vc =  0.1005   OM = 0.0115
Zc=   0.2916 Zcrat=   1.1600 Zceos=  0.3382 Vceos= 0.1165
ac=   2.3038    b =   0.0304  del1=  0.5000    k = 1.5408
CARBON DIOXIDE(2) 
Tc= 304.2100   Pc =  73.8300   Vc =  0.0940   OM = 0.2236
Zc=   0.2744 Zcrat=   1.1600 Zceos=  0.3183 Vceos= 0.1090
ac=   3.8521    b =   0.0279  del1=  1.8533    k = 2.2029
n-DECANE(3)       
Tc= 617.7000   Pc =  21.1000   Vc =  0.6521   OM = 0.4923
Zc=   0.2679 Zcrat=   1.1600 Zceos=  0.3108 Vceos= 0.7565
ac=  56.6611    b =   0.1921  del1=  2.2395    k = 3.1134
 
 Tc, Pc and Vc are given in K, bar and L/mol respectively
 
   Kij MATRIX
METHANE(1)        
CARBON DIOXIDE(2)    0.10000
n-DECANE(3)          0.00000   0.09100
 
   LIJ MATRIX
METHANE(1)        
CARBON DIOXIDE(2)    0.00000
n-DECANE(3)         -0.14552   0.00000
 
  Combining rules:
  0: Classical or van der Waals 
 
Molar fractions:  0.250 0.500 0.250
  x    0.2500E+00  0.5000E+00  0.2500E+00
  y    0.5166E+00  0.

In [31]:
env.plot()

TypeError: unbound method __init__() must be called with UserDict instance as first argument (got WeakValueDictionary instance instead)

## Graficación de envolventes

In [ ]:
fig = env.plot()
fig

In [ ]:
multiplot??

La figura puede manipularse a posteriori. Por ejemplo

In [ ]:
ax = fig.get_axes()[0]
ax.set_yticks([0] + ax.get_yticks()[1:])
fig

In [ ]:
ax.set_ylim((-50/3, 250))
fig

Pero también, acepta algunos parámetros de configuración en la llamada. Por ejemplo, el parámetro `format` permite definir el estilo

In [ ]:
env.plot(format='k')   # envolvente en linea negra continua

In [ ]:
env.plot(critical_point='^', format='|y')    # envolvente en amarillo punteado y punto critico como un triangulo

## Datos experimentales

Se pueden asociar datos experimentales de una envolvente a una mezcla a traves de `experimental_envelope`. Por ejemplo, a modo de ejemplo, alteramos los datos de la envolvente calculada a modo de datos experimentales.

In [ ]:
n = env.p.size

p = env.p[np.arange(0, n, 7)]  * 1.1
t = env.t[np.arange(0, n, 7)]
exp_env = m.experimental_envelope(t, p)
exp_fig = exp_env.plot()
exp_fig

Los graficos pueden encadenarse. Por ejemplo, podemos graficar la envolvente simulada y nuestra envolvente *experimental*

In [ ]:
env.plot(exp_fig)

## Cálculo de flashes

Un flash se representa como un objeto que produce dos mezclas con los mismos compuestos que la mezcla de entrada pero distinta fraccion. 

In [ ]:
flash = m.get_flash(setup, 400, 100)

In [ ]:
flash.vapour_mixture

In [ ]:
flash.liquid_mixture.z

O, lo que es lo mismo

In [ ]:
flash.x

`liquid_mixture` y `vapour_mixture` son mezclas, por lo que podemos simular sus envolventes con el mismo setup. Luego, grafiquemos todo junto

In [ ]:
le = flash.liquid_mixture.get_envelope(setup)
ve = flash.vapour_mixture.get_envelope(setup)

env.plot(ve.plot(le.plot()))

In [ ]:
fig = env.plot()

In [ ]:
fig.